export const initialServices = [
  {
    id: 1,
    name: "غسيل خارجي",
    type: "سيارات",
    price: 80,
    unit: "ثابت",
    count: 12,
    description: "غسيل وتنظيف الهيكل الخارجي للسيارة",
    active: true,
  },
  {
    id: 2,
    name: "غسيل داخلي وخارجي",
    type: "سيارات",
    price: 120,
    unit: "ثابت",
    count: 8,
    description: "تنظيف كامل للسيارة من الداخل والخارج",
    active: true,
  },
  {
    id: 3,
    name: "تلميع كامل",
    type: "سيارات",
    price: 250,
    unit: "ثابت",
    count: 4,
    description: "تلميع كامل للسيارة",
    active: true,
  },
  {
    id: 4,
    name: "غسيل سجاد",
    type: "سجاد",
    price: 30,
    unit: "متر",
    count: 0,
    description: "غسيل وتنظيف السجاد",
    active: true,
  },
  {
    id: 5,
    name: "تنظيف سجاد فاخر",
    type: "سجاد",
    price: 45,
    unit: "متر",
    count: 0,
    description: "تنظيف عميق للسجاد الفاخر",
    active: true,
  },
]

export const initialCustomers = [
  {
    id: 1,
    name: "أحمد حسن",
    phone: "01000000000",
    address: "القاهرة",
    notes: "عميل تجريبي",
    cars: 1,
    carpets: 2,
  },
  {
    id: 2,
    name: "محمد علي",
    phone: "01111111111",
    address: "الجيزة",
    notes: "",
    cars: 2,
    carpets: 0,
  },
  {
    id: 3,
    name: "محمود إبراهيم",
    phone: "01222222222",
    address: "مدينة نصر",
    notes: "يفضل التواصل قبل الاستلام",
    cars: 0,
    carpets: 3,
  },
]

export const initialCars = [
  {
    id: 1,
    customerId: 1,
    plateNumber: "أ ب ج 1234",
    brand: "Toyota",
    model: "Corolla",
    color: "أبيض",
    year: 2022,
    notes: "غسيل أسبوعي",
    active: true,
  },
  {
    id: 2,
    customerId: 2,
    plateNumber: "د هـ و 5678",
    brand: "Hyundai",
    model: "Elantra",
    color: "أسود",
    year: 2021,
    notes: "",
    active: true,
  },
  {
    id: 3,
    customerId: 2,
    plateNumber: "س ص ع 9012",
    brand: "Kia",
    model: "Sportage",
    color: "رمادي",
    year: 2023,
    notes: "تنظيف داخلي فقط",
    active: true,
  },
]

export const initialInvoices = []
export const initialExpenses = []